name: Build Telegram APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build APK
        run: ./gradlew assembleArm64V8aRelease

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: telegram-apk
          path: Telegram/TMessagesProj/build/outputs/apk/arm64-v8a/release/*.apk
